services:
  idp:
    container_name: idp
    build: .
    ports:
      - "19011:8000"
    environment:
      - VLLM_API_URL=YOUR_VLLM_API_URL
      - VLLM_GEN_API_PORT=YOUR_VLLM_GEN
      - VLLM_GEN_MODEL_NAME=YOUR_VLLM_GEN_MODEL_NAME
