[project]
name = "intelligent-document-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.128.6",
    "gunicorn>=25.0.3",
    "httpx>=0.28.1",
    "pymupdf>=1.25.0",
    "python-multipart>=0.0.22",
    "uvicorn>=0.40.0",
]
